name: Publish Package to GitHub Packages

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: "bun install --ignore-scripts"
      - run: "bun lint"

  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: "bun install --ignore-scripts"
      - run: "bun test"

  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: '@sylvain12'
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.3
      - run: bun install
      - name: Create Realease Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          run: npm run build
      - name: Publish
        if: steps.changesets.output.hasChangesets == 'false'
        run: npm publish
          



      
